### ISSUE TITLE
とりあえず現状の仕様をだれが責任をもって登録するか

### ISSUE THREAD

**Issue by katsusuke** [mk-system/rules#2]
表題の件を議論したいです。

**Comment by katsusuke** [comment]
@MKJP-Takashi-Ohta お願い致します。

**Comment by MKJP-Takashi-Ohta** [comment]
- メイン　->　@MKJP-Takashi-Ohta 
- サブ　->　@t-ishihara 

ということで…

**Comment by MKJP-Takashi-Ohta** [comment]
よくよく考えたら　現状ルール　あんまり知らないや…
社員でちゃんと知ってる人いる？？

**Comment by katsusuke** [comment]
清水が登録します
